[tool.poetry]
name = "packs"
version = "1.0.0"
description = "Some of the packs on https://vanillatweaks.net"
authors = ["VanillaTweaks <team@vanillatweaks.net>"]
packages = [
    { include = "scripts" },
]

[tool.poetry.scripts]
build = "scripts.build:build"
watch = "scripts.build:watch"

[tool.poetry.dependencies]
python = "^3.10"
beet = ">=0.67.1"
mecha = ">=0.52.2"
bolt = ">=0.7.1"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"

[tool.pyright]
typeCheckingMode = "strict"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
